

import pyautogui
pyautogui.FAILSAFE=False
from win32api import GetSystemMetrics
import os
print("SalesMate + Backup Menu Test")
path="D:/SMP"
if not os.path.exists(path):
    os.makedirs(path)
width=GetSystemMetrics(0)
height=GetSystemMetrics(1)
print("click on the bottom left to launch the start menu")
pyautogui.click(0,height)
print("Select the SalesMate + Application")
pyautogui.typewrite("SalesMate +")
print("Press Enter Key to Launch SalesMate + Application and wait for 10 sec")
pyautogui.press("enter",1,10)
print("Press Enter Key again to close the tip of the Day Dialog")
pyautogui.press("enter",1,2)
print("Now alt and f shortcut key in SalesMate to invoke the file root menu")
pyautogui.press(['alt','f'],1,2)
print("Now press 'b' to invoke the backup folder dialog")
pyautogui.press("b",1,2)
print("Go to D drive")
pyautogui.press("down")
pyautogui.press("down")
pyautogui.press("down")
pyautogui.press("down")
pyautogui.press("down")
pyautogui.press("down")
pyautogui.press("down")
pyautogui.press("down")
pyautogui.press("down",1,1)
print("Now press right arrow key to expand the tree")
pyautogui.press("right")
print("Go to SMP folder")
pyautogui.typewrite("smp")
print("Press enter key to back up data")
pyautogui.press("enter",1,3)
print("Press enter again to close the ok button")
pyautogui.press("enter")
print("Press ctrl and a to add customer details")
pyautogui.press(['ctrl','a'])
pyautogui.press("enter",1,2)
pyautogui.press("enter",1,3)
print("First name")
pyautogui.typewrite("Anjali")
pyautogui.press("enter",1,2)
print("Last name")
pyautogui.typewrite("M")
pyautogui.press("enter",1,2)
print("Title")
pyautogui.typewrite("Ms")
pyautogui.press("enter",1,2)
print("Address")
pyautogui.typewrite("abcd villa,pala1")
pyautogui.press("enter",1,2)
print("Phone number")
pyautogui.typewrite("9876543210")
pyautogui.press("enter",1,2)
print("Email id")
pyautogui.typewrite("annamathew@gmail.com")
pyautogui.press("enter",1,2)
print("Category")
pyautogui.press("enter")
print("Comment")
pyautogui.typewrite("abcdefgh")
pyautogui.press("enter")
pyautogui.press("enter")
pyautogui.press("enter")
pyautogui.press("enter",1,2)
print("Customer image")
pyautogui.typewrite("SMPBanner.bmp")
pyautogui.press("enter",1,2)
pyautogui.press("enter",1,2)
pyautogui.press("enter",1,2)
